---
- name: Extract artifact.tar.gz into /home/ubuntu
  unarchive:
    src:  artifact.tar.gz
    dest: /home/ubuntu

- name: npm install
  command: npm install
  args:
    chdir: /home/ubuntu

- name: pm2 stop default
  command: pm2 stop default
  args:
    chdir: /home/ubuntu

- name: pm2 start npm -- start
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu
...