---
- name: "useradd node_exporter without creating home"
  become: true
  user:
    name: node_exporter
    create_home: no

- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin"
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'

- name: delete file node_exporter-1.0.1.linux-amd64.tar.gz
  file:
    state: absent
    path: /tmp/node_exporter-1.0.1.linux-amd64.tar.gz

- name: delete file node_exporter-1.0.1.linux-amd64
  file:
    state: absent
    path: /tmp/node_exporter-1.0.1.linux-amd64
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes
...